name: Daily Crossword Scraper


on:
schedule:
# 19:00 UTC ≈ 05:00 Australia/Melbourne (AEST). Adjust for DST as needed.
- cron: "0 19 * * *"
workflow_dispatch:


jobs:
scrape:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v4
- name: Set up Python
uses: actions/setup-python@v5
with:
python-version: "3.11"
- name: Install deps
run: pip install -r requirements.txt
- name: Run scraper
run: python scraper/run.py
- name: Commit results
run: |
git config --local user.email "actions@github.com"
git config --local user.name "github-actions"
git add todays-crossword.json
git diff --quiet && echo "No changes" || git commit -m "chore: update todays-crossword.json"
- name: Push
uses: ad-m/github-push-action@v0.8.0
with:
github_token: ${{ secrets.GITHUB_TOKEN }}
